{ pkgs, ... }: {
  environment.gnome.excludePackages = (with pkgs; [
    baobab
    evolution
    evolution-data-server
    evolution-data-server-gtk4
    evolution-ews
    gfbgraph
    gnome-connections
    gnome-console
    gnome-extension-manager
    gnome-online-accounts
    gnome-photos
    gnome-text-editor
    gnome-tour
    gnome-tour
    gnome-user-docs
    gnome-video-effects
    gnomeExtensions.applications-menu
    gnomeExtensions.auto-move-windows
    gnomeExtensions.launch-new-instance
    tracker
    tracker-miners
    xterm
  ]) ++ (with pkgs.gnome; [
    accerciser
    adwaita-icon-theme
    aisleriot
    anjuta
    atomix
    caribou
    cheese
    dconf-editor
    devhelp
    eog
    epiphany
    evince
    file-roller
    five-or-more
    four-in-a-row
    geary
    gedit
    ghex
    gitg
    gnome-applets
    gnome-backgrounds
    gnome-boxes
    gnome-calculator
    gnome-calendar
    gnome-characters
    gnome-chess
    gnome-clocks
    gnome-color-manager
    gnome-contacts
    gnome-dictionary
    gnome-disk-utility
    gnome-flashback
    gnome-font-viewer
    gnome-initial-setup
    gnome-klotski
    gnome-logs
    gnome-mahjongg
    gnome-maps
    gnome-mines
    gnome-music
    gnome-nibbles
    gnome-notes
    gnome-online-miners
    gnome-packagekit
    gnome-panel
    gnome-power-manager
    gnome-remote-desktop
    gnome-robots
    gnome-screenshot
    gnome-shell-extensions
    gnome-software
    gnome-sound-recorder
    gnome-sudoku
    gnome-system-monitor
    gnome-taquin
    gnome-tetravex
    gnome-themes-extra
    gnome-tweaks
    gnome-user-share
    gnome-weather
    gpaste
    gtkhtml
    hitori
    iagno
    lightsoff
    metacity
    nautilus-python
    polari
    pomodoro
    quadrapassel
    rygel
    seahorse
    simple-scan
    swell-foop
    tali
    totem
    vinagre
    yelp
    yelp-xsl
  ]);
}
